apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      imagePullSecrets:
      - name: harbor  # 用于拉取私有镜像的 Secret
      containers:
      - name: infer-api
        image: demo
        command: ["gunicorn"]
        args:
        - "app.main:app"
        - "--bind"
        - "0.0.0.0:8000"
        - "--workers"
        - "4"
        - "--worker-class"
        - "uvicorn.workers.UvicornWorker"
        - "--worker-connections"
        - "1000"
        - "--keep-alive"
        - "5"
        - "--max-requests"
        - "1000"
        - "--timeout"
        - "60"
        - "--graceful-timeout"
        - "30"
        - "--access-logfile"
        - "-"
        - "--error-logfile"
        - "-"
        - "--log-level"
        - "info"
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "false"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30008
  type: NodePort 
